Repository JuliaDynamics/RecurrenceAnalysis.jl, pull requests merged in 2019-01, with the labels that each got.

#36 == and != operators for AbstractRecurrenceMatrix
  src/matrices.jl
Labels: bug

#35 Histograms
  src/RecurrenceAnalysis.jl
  src/histograms.jl
  src/rqa.jl
  src/windowed.jl
  test/runtests.jl
  test/smallmatrix.jl
Labels: clarity, enhancement

#42 zero RQA parameters with warning for empty histograms
  src/rqa.jl
Labels: clarity

#44 doc updates for histogram stuff
  .travis.yml
  appveyor.yml
  src/histograms.jl
  src/rqa.jl
  src/windowed.jl
Labels: documentation

#46 _computescale methods for maximum and mean
  src/matrices.jl
Labels: documentation, performance

#54 Fix `trend`
  src/rqa.jl
  test/smallmatrix.jl
Labels: bug

#55 fix `_computescale(scale::typeof(mean), x, y, ...)`
  src/matrices.jl
Labels: enhancement

#56 clean code and docstrings + improve performance
  src/RecurrenceAnalysis.jl
  src/histograms.jl
  src/matrices.jl
  src/rqa.jl
  test/smallmatrix.jl
Labels: clarity, documentation, performance

#61 Change return value of rqa to named Tuple
  src/rqa.jl
  src/windowed.jl
  test/dynamicalsystems.jl
  test/smallmatrix.jl
Labels: performance

#63 specialize _computescale for identical inputs
  src/matrices.jl
Labels: performance

#68 multiply TREND x10^3
  src/rqa.jl
  test/smallmatrix.jl
Labels: clarity
